<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Equipamento</name>
   <tag></tag>
   <elementGuidId>626e7af1-ecce-481f-bc98-be8db3115cf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/nav/ul/li/ul/li[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(7) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9a98c849-f0b5-4382-bf2f-e3e16924890b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cadastros/equipamento</value>
      <webElementGuid>0ef1972b-bf29-49d0-90ab-d7ee5bb1538c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Equipamento</value>
      <webElementGuid>bc567958-1320-4804-b973-d5e311e367f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/nav[@class=&quot;navbar&quot;]/ul[@class=&quot;navbar-list&quot;]/li[@class=&quot;navbar-item&quot;]/ul[@class=&quot;sub-menu&quot;]/li[7]/a[1]</value>
      <webElementGuid>e3db6370-08f5-4c68-81d7-c404ce8ef07b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav/ul/li/ul/li[7]/a</value>
      <webElementGuid>11e3421a-d12b-4fb7-8c47-1022a79cc647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Equipamento')]</value>
      <webElementGuid>461c69f0-4b34-4369-8fe4-43a731c97331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Máquina'])[1]/following::a[1]</value>
      <webElementGuid>7d2fcaad-98b6-466a-8dd4-6e26f9a0677e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modelo'])[1]/following::a[2]</value>
      <webElementGuid>7b17f64d-237a-40c4-91a4-78c05071a987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Componente'])[1]/preceding::a[1]</value>
      <webElementGuid>32301d66-e719-4ef9-a254-f42c4409efdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manual'])[1]/preceding::a[2]</value>
      <webElementGuid>1933e61d-197d-4014-8035-8c9a3dc3c347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Equipamento']/parent::*</value>
      <webElementGuid>174ec658-7519-40ad-9cac-87e7ee148c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cadastros/equipamento')]</value>
      <webElementGuid>fe046663-5a6c-4bd5-8128-ecdef8bc580d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>b446f695-96ca-4ae1-8aac-d02c66a1d4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cadastros/equipamento' and (text() = 'Equipamento' or . = 'Equipamento')]</value>
      <webElementGuid>d5e8488f-8bed-4566-b9fb-93a9c42d53bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
