<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gerais</name>
   <tag></tag>
   <elementGuidId>5fd4cb0d-dbcc-409d-8bff-159b72d1e440</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/nav/ul/li[4]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.sub-menu > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2fc8984e-ce22-40d1-bf35-5c6bb23c71be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/indicadores/relatorios/gerais</value>
      <webElementGuid>e586253d-5a72-4325-a663-60277082be9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gerais</value>
      <webElementGuid>84360c23-023a-4e71-aa10-3c9830305be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/nav[@class=&quot;navbar&quot;]/ul[@class=&quot;navbar-list&quot;]/li[@class=&quot;navbar-item&quot;]/ul[@class=&quot;sub-menu&quot;]/li[1]/a[1]</value>
      <webElementGuid>0168d654-f814-43e5-8784-6daea5138e4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav/ul/li[4]/ul/li/a</value>
      <webElementGuid>c32321ab-f363-44d8-813e-bf13a7a6eaee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Gerais')]</value>
      <webElementGuid>5ad042fd-33cf-468a-826f-bf6ba0484578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Equipamentos'])[1]/preceding::a[2]</value>
      <webElementGuid>6b501b61-7705-497b-816a-f1bf6f6e97b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adicionar'])[1]/preceding::a[2]</value>
      <webElementGuid>36f02c29-de34-4312-b9e9-b4980936348d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gerais']/parent::*</value>
      <webElementGuid>1c00592d-a581-449c-b2ca-c61fdfcf95dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/indicadores/relatorios/gerais')]</value>
      <webElementGuid>fc38ba67-860c-46d1-a2a3-c5c294031ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li/a</value>
      <webElementGuid>e37f9ed6-9024-4f4a-9a8c-822479a7c55d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/indicadores/relatorios/gerais' and (text() = 'Gerais' or . = 'Gerais')]</value>
      <webElementGuid>c86ce733-7239-4280-ab0e-152346cd906f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
