<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Logar</name>
   <tag></tag>
   <elementGuidId>d09bb8ca-9e84-4e18-8689-0ed6096e95e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.logar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>93c520e9-e55b-4ec1-a617-3b4cd1b3e006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logar</value>
      <webElementGuid>83b4e666-1bd1-4380-97ec-6fe9257f384d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logar</value>
      <webElementGuid>8e8406a9-43c1-4c8e-a633-aa2ed546729e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;tittleLogin&quot;]/div[@class=&quot;containerLogin&quot;]/div[@class=&quot;campos&quot;]/button[@class=&quot;logar&quot;]</value>
      <webElementGuid>77bac42f-9931-4838-90da-39fe0e8ac96f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/button</value>
      <webElementGuid>3f696479-fa31-44dc-bbb2-0ad02889b9c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entrar'])[1]/following::button[1]</value>
      <webElementGuid>62cc6ac9-111b-400d-89b8-f71a70fbeeeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/preceding::button[1]</value>
      <webElementGuid>936d2bc7-d532-4a83-80cf-5bd7faf66469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logar']/parent::*</value>
      <webElementGuid>7eb13604-f9cc-4d0d-b769-dc80fc2078dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>4aeaa278-6f95-4ef0-86ec-ac64a7d49bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Logar' or . = 'Logar')]</value>
      <webElementGuid>567f4cee-4c0e-48e4-973d-9b97c861bfb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
