<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nav_CadastrosExecuoIntegraesRelatriosConfiguraes</name>
   <tag></tag>
   <elementGuidId>bc371a9d-6544-4ccf-ae1e-af422b883985</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nav.navbar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/nav</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nav</value>
      <webElementGuid>31c13aff-3457-4e52-9c65-3d1b99a2b3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar</value>
      <webElementGuid>999b0ae3-566e-40b8-9748-b198357c4bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CadastrosExecuçãoIntegraçõesRelatóriosConfigurações</value>
      <webElementGuid>dceb6686-edb9-4e63-8912-292e7d4a3552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/nav[@class=&quot;navbar&quot;]</value>
      <webElementGuid>dd382690-9519-4166-ab37-8ce7ba1aaf7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav</value>
      <webElementGuid>290d0285-bf01-48a2-bf07-341e749da55c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav</value>
      <webElementGuid>29e06246-110b-4ff8-9a70-c8ebde8ee800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nav[(text() = 'CadastrosExecuçãoIntegraçõesRelatóriosConfigurações' or . = 'CadastrosExecuçãoIntegraçõesRelatóriosConfigurações')]</value>
      <webElementGuid>a0f43314-93b2-45f6-9c1b-afb289f8facf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
