<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Selecione uma opoMaquinasEquipamento_7e377f</name>
   <tag></tag>
   <elementGuidId>5bd5280e-9146-4df6-be9c-2f4ab422dc26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a1a722d4-0c76-4638-91d5-2fb5fa3d3926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selecione uma opçãoMaquinasEquipamentosSetoresOrdens de Serviço</value>
      <webElementGuid>b7f68a21-9f60-48a6-a4b2-571c71ae4301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;relatoriosGerais&quot;]/div[@class=&quot;containerRelatorio&quot;]/select[1]</value>
      <webElementGuid>d846b115-a31c-4699-bc8b-f8dbffd11c6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/select</value>
      <webElementGuid>136b9226-2176-48b7-9944-18465da4d702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gerar PDF'])[1]/preceding::select[1]</value>
      <webElementGuid>9759d905-1881-487b-84df-e0739d494344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>97d13d07-314b-4fa5-b803-82a8fe554a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'Selecione uma opçãoMaquinasEquipamentosSetoresOrdens de Serviço' or . = 'Selecione uma opçãoMaquinasEquipamentosSetoresOrdens de Serviço')]</value>
      <webElementGuid>c437413f-3112-468f-9f91-d52d05291009</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
