<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Inativo</name>
   <tag></tag>
   <elementGuidId>bff5eb6d-7b00-44f2-a8d8-ac5d7c63b883</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(4)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/table/tbody/tr/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e5df8fcf-4468-40df-b151-3738a5ffbb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>10e6d957-8d58-4de1-81d7-d99e5869ebe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inativo</value>
      <webElementGuid>c7db4814-8e69-4d33-ae63-e8a1b94a4c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;containerConsulta&quot;]/div[2]/table[@class=&quot;table&quot;]/tbody[1]/tr[@class=&quot;clickable-row&quot;]/td[4]</value>
      <webElementGuid>9b3ec934-8e5a-4066-815e-a18ba63cfba3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/table/tbody/tr/td[4]</value>
      <webElementGuid>586c40ff-4ec1-4dbf-bad9-b976bd859faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kollmorgen AKM52. Potência Nominal: 2.5 kW, Tensão Nominal: 230V, Torque Nominal: 15 Nm'])[1]/following::td[1]</value>
      <webElementGuid>5d2325dd-f463-468c-b4d0-3059be5345aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kollmorgen AKM52'])[1]/following::td[2]</value>
      <webElementGuid>8915ccad-1356-4ddf-9131-cc7fc1fbf58c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;'])[1]/preceding::td[1]</value>
      <webElementGuid>3a64c99b-2fd4-4af9-bc77-d3ff9b72cf8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Inativo']/parent::*</value>
      <webElementGuid>8752f832-f0ec-4a28-9148-aade91064648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]</value>
      <webElementGuid>831fa8b7-158e-4685-9d54-5ee06c709192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Inativo' or . = 'Inativo')]</value>
      <webElementGuid>f64e02a4-8fae-457a-b107-52d92d7e416a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
